steps:
  #step 1
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/$PROJECT_ID/orderbook:latest || exit 0"]
  #step 2
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/orderbook:$TAG_NAME",
        "-t",
        "gcr.io/$PROJECT_ID/orderbook:latest",
        ".",
      ]
  #step 3
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "k8s/"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=europe-central2-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=deploy-cicd"
  #step 4
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment",
        "orderbook",
        "orderbook=gcr.io/$PROJECT_ID/orderbook:$TAG_NAME",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=<europe-central2-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=deploy-cicd"
# push images to Google Container Registry with tags
images:
  [
    "gcr.io/$PROJECT_ID/<app-name>:$TAG_NAME",
    "gcr.io/$PROJECT_ID/<app-name>:latest",
  ]
